# Generated by Django 2.1.2 on 2018-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la oferta')),
                ('price', models.CharField(max_length=6, verbose_name='Precio oferta')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ['title'],
            },
        ),
    ]
